version: '3'
networks:
    network2:
        name: network2
services:
    nginx1:
        container_name: ngingx1
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./newnginx.conf:/etc/nginx/conf.d/default.conf
            - ./app:/app
        networks:
            - network2
        depends_on:
            - php1
            - mysql1
    php1:
        container_name: php1
        build: ./images
        volumes:
            - ./app:/app
        networks:
            - network2
        depends_on:
            - mysql1
    mysql1:
        container_name: mysql11
        image: mysql
        volumes:
            - ./mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=hi
        networks:
            - network2
    phpmyadmin1:
        container_name: phpmyadmin1
        image: phpmyadmin
        ports:
            - 1500:80
        environment:
            - PMA_HOST=mysql1
        networks:
            - network2
        depends_on:
            - mysql1

    